[package]
name = "biterator"
version = "0.1.0"
edition = "2021"
authors = ["Thomas Castleman <thomascastleman0@gmail.com>"]
description = "A crate for iterating over individual bits in a byte slice"

[dependencies]
